### ISSUE TITLE
IconOnly attribute for specialized button

### ISSUE THREAD

**Issue by kilya11** [mll-lab/react-components#105]
In some cases there is a need for a button with only one icon. To achieve this use:

`<Button icon={<PlusOutlined />} />`

Luckily there is a specialized button with this icon:

`<CreateButton>{''}</CreateButton>`

The problem is, it has default children, thus they must be overwritten with that empty-string-hack.
To increase semantics we can add the `iconOnly` boolean attribute. The name comes from CSS class `ant-btn-icon-only`, which the element becomes in this case.
Final use:

`<CreateButton iconOnly />`

**Comment by spawnia** [comment]
We have a guideline that specifically forbids the usage of buttons without text. It might be necessary in certain edge cases, but I don't think we should add a feature to encourage bad UI.

**Comment by kilya11** [comment]
These Elements are used in applications with high information density, thus it should be a valid case. Otherwise use ant directly.

**Comment by spawnia** [comment]
I can see how the semantic clarity of the source code is improved. Even though we should generally avoid UIs that are crowded enough to warrant usage of non-textually described buttons, it is preferrable to mark those with a dedicated prop rather than a workaround.
