### ISSUE TITLE
Visualize disabled state of buttons

### ISSUE THREAD

**Issue by mic-web** [mll-lab/react-components#106]
Currently, the buttons look the same when disabled or not.

This should be improved by choosing a design that's more closely to the default AntD disabed look:

![image](https://user-images.githubusercontent.com/4804412/143890161-64439634-0dc5-4ebf-aacf-248aa548a2bb.png)

**Comment by spawnia** [comment]
Sounds good. The storybook should be extended with an example and/or controls, currently lacking in https://mll-lab.github.io/react-components/?path=/story/button--default

**Comment by mic-web** [comment]
Note: It has to be ensured that the disabled state is easily distinguishable from all other default button styles, especially the grey `<InfoButton />`
