### ISSUE TITLE
CSS classes missing

### ISSUE THREAD

**Issue by kilya11** [mll-lab/react-components#124]
The layout properties create special CSS classes to define proper elements width:

```tsx
import { Form } from '@mll-lab/react-components';

<Form.Item
        label="Label"
        name="field"
        labelCol={{ span: 8 }}
        wrapperCol={{ span: 16 }}
      >
        <Input />
</Form.Item>
```

![image](https://user-images.githubusercontent.com/4448508/151313130-5a3a8d92-eb4a-48b9-a8b4-72e3fb93aee3.png)

The `mll-ant-col-8` and `mll-ant-col-16` are missing. So the design is broken.

**Comment by kilya11** [comment]
https://github.com/ant-design/ant-design/pull/33969 👏

**Comment by kilya11** [comment]
https://github.com/ant-design/ant-design/releases/tag/4.18.7

**Comment by mic-web** [comment]
There's more that needs to be fixed to rename all used classes correctly:

https://github.com/ant-design/ant-design/pull/34494

**Comment by mic-web** [comment]
https://github.com/mll-lab/react-components/pull/150

**Comment by spawnia** [comment]
Is this fixed now?

**Comment by mic-web** [comment]
Yes, fixed 👍
