### ISSUE TITLE
Clear-Icon is placed over Down-Arrow in Select Box

### ISSUE THREAD

**Issue by donAlDente** [mll-lab/react-components#136]
### Description

When you have a `Select` component with the attribute `allowClear` the clear-Icon is placed upon the arrow icon of the dropdown.  When you try to open the dropdown and you try to click on the `down-arrow`, you accidentally clear the value from the select box, instead of opening the dropdown.

The Select-Box:
![image](https://user-images.githubusercontent.com/100780246/156375801-bb35c2ba-cbff-4e47-b8f3-0255642276a3.png)

The Icon when you hover over the select box with a value selected.
![image](https://user-images.githubusercontent.com/100780246/156375858-bb933435-b08c-4a44-93c8-dd54ed70e8ec.png)

### Desired behaviour
The `clear` icon should not be placed upon the `arrow-down` icon.

**Comment by spawnia** [comment]
This is the default behaviour of the base library - see https://ant.design/components/select. You can click anywhere else in the select box to open the dropdown instead.
