### ISSUE TITLE
Rendering of plate well content is not intuitive

### ISSUE THREAD

**Issue by SimBig** [mll-lab/react-components#138]
Right now the Well of the Plate has a css-flex property that centers the content. `
``` 
 display: 'flex',
 justifyContent: 'center',
 alignItems: 'center',
``` 

This css will render the react nodes in a well with the flex property:
eg: `
 content: (
      <>
        <p>Kontrolle</p>
        <br />
        Test sdsd
        <p>Kontrolle</p>
      </>
    ),` will result in:

![image](https://user-images.githubusercontent.com/26680884/157200569-6e9467a9-ddc8-40e1-8434-f5e85a1519a1.png)

either we should delete this flex property and the user of the component should be responsible for the formatting of the plate content 
eg: 
![image](https://user-images.githubusercontent.com/26680884/157201721-c4ce71c5-b9e5-4e6f-9f3d-0e42b1594963.png)

or we should add a `flexDirection: "column",` so that the content will be rendered column-wise
![image](https://user-images.githubusercontent.com/26680884/157201830-15602412-b985-400c-a8f5-df89982f4643.png)

**Comment by SimBig** [comment]
@spawnia what's your opinion about this issue?

**Comment by spawnia** [comment]
Not superimposing styling constraints on child content seems reasonable.
