### ISSUE TITLE
Fix width of InputNumber

### ISSUE THREAD

**Issue by kilya11** [mll-lab/react-components#230]
The `<InputNumber>` component has the fixed width of 90px, see https://mll-lab.github.io/react-components/?path=/story/input--number

![grafik](https://user-images.githubusercontent.com/4448508/233003751-a91e538f-fa9f-432c-aa43-84a38c2037fb.png)

Because of the `.mll-ant-input-number { width: 90px }`.

The width should be flexible.

**Comment by spawnia** [comment]
Resolved with https://github.com/mll-lab/react-components/pull/233/commits/c8427cc6369d222963b9a277e9e81e7c25af40e3
