### ISSUE TITLE
CSS that applies to multiple classes does not work

### ISSUE THREAD

**Issue by spawnia** [mll-lab/react-components#30]
Already happened to others, closed issue from antd: https://github.com/ant-design/ant-design/issues/20369.

The LESS behaviour that causes this: http://lesscss.org/features/#parent-selectors-feature-multiple-

Possible solution: https://gist.github.com/sbusch/a90eafaf5a5b61c6d6172da6ff76ddaa

More discussion: https://github.com/ant-design/ant-design/issues/9363

**Comment by me6iaton** [comment]
I used mixins to get around the nesting problem

#ant {
  .airy-collapse() {
    @ant-prefix: 'ant-airy';
    @collapse-prefix-cls: ~'@{ant-prefix}-collapse';
    @collapse-content-padding: 16px 0px;

    @import (multiple) '../../../node_modules/antd/es/collapse/style/index-pure.less';

    .@{collapse-prefix-cls} {
      & > &-item {
        > .@{collapse-prefix-cls}-header {
          font-weight: 500;
        }
      }
    }
  }
}

#ant.airy-collapse();
