### ISSUE TITLE
Input Component does not render correctly

### ISSUE THREAD

**Issue by SimBig** [mll-lab/react-components#40]
Expected behavior:
![image](https://user-images.githubusercontent.com/26680884/116527897-763dd500-a8db-11eb-95f2-f6fb89d7c4fe.png)

Actual behavior:
![image](https://user-images.githubusercontent.com/26680884/116527658-3aa30b00-a8db-11eb-8df6-fe7613638231.png)

This css ist applied to the actual antd component but not any more to the mll-component:
![image](https://user-images.githubusercontent.com/26680884/116528124-bbfa9d80-a8db-11eb-9427-1d2819740e85.png)

Possibly connected/duplicate of https://github.com/mll-lab/react-components/issues/30

**Comment by spawnia** [comment]
Caused by https://github.com/ant-design/ant-design/pull/31479
